### ISSUE TITLE
subprocess.run(["bsdtar", "xfp", iso_file, "-C", iso_dir], check=True)

### ISSUE THREAD

**Issue by MrAmbiG** [newAM/unattended_ubuntu#2]
Traceback (most recent call last):
  File "./make.py", line 69, in <module>
    main()
  File "./make.py", line 30, in main
    subprocess.run(["bsdtar", "xfp", iso_file, "-C", iso_dir], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bsdtar'

**Comment by newAM** [comment]
This requirement is in the readme.

![image](https://user-images.githubusercontent.com/7845120/89481242-341ca400-d74c-11ea-9af4-a4e6324da256.png)

If you have a suggestion for a better tool please let me know!
